name: Discord Notify (Bot)

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set commit message
        run: |
          echo "MESSAGE=${{ github.event.head_commit.message || 'No commit message' }}" >> $GITHUB_ENV

      - name: Send Discord message via Bot
        run: |
          JSON=$(jq -n \
            --arg message "$MESSAGE" \
            '{
              content: "<@&1523330739335205014>",
              embeds: [
                {
                  title: "Website Update",
                  description: ("**New Version available!**\n\nVersion: **" + "**\n\n**Changelog:**\n" + $message),
                  color: 5763719,
                  footer: {
                    text: "Website • https://kittys-plugins.net"
                  }
                }
              ]
            }')

          curl -X POST "https://discord.com/api/v10/channels/1523330691121676429/messages" \
            -H "Authorization: Bot ${{ secrets.DISCORD_BOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON"
